//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacktestingSoftware.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AlgorithmFileName {
            get {
                return ((string)(this["AlgorithmFileName"]));
            }
            set {
                this["AlgorithmFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataFileName {
            get {
                return ((string)(this["DataFileName"]));
            }
            set {
                this["DataFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime StartDate {
            get {
                return ((global::System.DateTime)(this["StartDate"]));
            }
            set {
                this["StartDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime EndDate {
            get {
                return ((global::System.DateTime)(this["EndDate"]));
            }
            set {
                this["EndDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ValueOfSliderOne {
            get {
                return ((int)(this["ValueOfSliderOne"]));
            }
            set {
                this["ValueOfSliderOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ValueOfSliderTwo {
            get {
                return ((int)(this["ValueOfSliderTwo"]));
            }
            set {
                this["ValueOfSliderTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ValueOfSliderThree {
            get {
                return ((int)(this["ValueOfSliderThree"]));
            }
            set {
                this["ValueOfSliderThree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ValueOfSliderFour {
            get {
                return ((int)(this["ValueOfSliderFour"]));
            }
            set {
                this["ValueOfSliderFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ValueOfSliderFive {
            get {
                return ((int)(this["ValueOfSliderFive"]));
            }
            set {
                this["ValueOfSliderFive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ValueOfSliderSix {
            get {
                return ((int)(this["ValueOfSliderSix"]));
            }
            set {
                this["ValueOfSliderSix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int RoundLotSize {
            get {
                return ((int)(this["RoundLotSize"]));
            }
            set {
                this["RoundLotSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100000")]
        public string Capital {
            get {
                return ((string)(this["Capital"]));
            }
            set {
                this["Capital"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string AbsTransactionFee {
            get {
                return ((string)(this["AbsTransactionFee"]));
            }
            set {
                this["AbsTransactionFee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string RelTransactionFee {
            get {
                return ((string)(this["RelTransactionFee"]));
            }
            set {
                this["RelTransactionFee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string PricePremium {
            get {
                return ((string)(this["PricePremium"]));
            }
            set {
                this["PricePremium"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveFileName {
            get {
                return ((string)(this["SaveFileName"]));
            }
            set {
                this["SaveFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection IndicatorPanels {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IndicatorPanels"]));
            }
            set {
                this["IndicatorPanels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRealTimeEnabled {
            get {
                return ((bool)(this["IsRealTimeEnabled"]));
            }
            set {
                this["IsRealTimeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StockSymbolForRealTime {
            get {
                return ((string)(this["StockSymbolForRealTime"]));
            }
            set {
                this["StockSymbolForRealTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Minute")]
        public string Barsize {
            get {
                return ((string)(this["Barsize"]));
            }
            set {
                this["Barsize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsAlgorithmUsingMaps {
            get {
                return ((bool)(this["IsAlgorithmUsingMaps"]));
            }
            set {
                this["IsAlgorithmUsingMaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdditionalParameters {
            get {
                return ((string)(this["AdditionalParameters"]));
            }
            set {
                this["AdditionalParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDataFutures {
            get {
                return ((bool)(this["IsDataFutures"]));
            }
            set {
                this["IsDataFutures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int InnerValue {
            get {
                return ((int)(this["InnerValue"]));
            }
            set {
                this["InnerValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsMiniContract {
            get {
                return ((bool)(this["IsMiniContract"]));
            }
            set {
                this["IsMiniContract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MiniContractDenominator {
            get {
                return ((int)(this["MiniContractDenominator"]));
            }
            set {
                this["MiniContractDenominator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CalculationThreadCount {
            get {
                return ((int)(this["CalculationThreadCount"]));
            }
            set {
                this["CalculationThreadCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsNetWorthChartInPercentage {
            get {
                return ((bool)(this["IsNetWorthChartInPercentage"]));
            }
            set {
                this["IsNetWorthChartInPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string ThemeName {
            get {
                return ((string)(this["ThemeName"]));
            }
            set {
                this["ThemeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseRegularTradingHours {
            get {
                return ((bool)(this["UseRegularTradingHours"]));
            }
            set {
                this["UseRegularTradingHours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDataFromESignal11 {
            get {
                return ((bool)(this["IsDataFromESignal11"]));
            }
            set {
                this["IsDataFromESignal11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MiniContractFactor {
            get {
                return ((int)(this["MiniContractFactor"]));
            }
            set {
                this["MiniContractFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsFullFuturePriceData {
            get {
                return ((bool)(this["IsFullFuturePriceData"]));
            }
            set {
                this["IsFullFuturePriceData"] = value;
            }
        }
    }
}
